# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 56aca95612e9cb15c1d8019806a4807f8932fd19831f6de8494124f38b17ba793db429f22b712f41a5810a1b49e9b5f2d487294d889a401484d2fa5b7f063e30

test:
  secret_key_base: 4da8b4085e5b32d6fdbcee33b39a8b7e0d4a3e484c993bb63c7830a0f846a4728bbdc3ad929f891de9a2d4633402fbe4072cb7194f7b0ea8380c882c19f67ae9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
